version: "2"

services:
  influxdb:
    image: dockerproxy-cwfr1.rd.francetelecom.fr/influxdb
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"

  chronograf:
    image: dockerproxy-cwfr1.rd.francetelecom.fr/chronograf
    volumes:
      - ./data/chronograf:/var/lib/chronograf
    ports:
      - "8888:8888"
    links:
      - influxdb

  rabbitmq-management:
    image: dockerproxy-cwfr1.rd.francetelecom.fr/rabbitmq:3-management
    hostname: "gdax-rabbit"
    ports:
      - "5672:5672"
      - "8080:15672"
    expose:
      - 5672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  gdax-auth-service:
    container_name: gdax-auth-service
    build:
      context: ..
      dockerfile: deploy/build/gdaxauthservice/Dockerfile
    image: gdaxauth-service:latest
    ports:
      - "28081:28081"
    expose:
      - 28081

  gdax-gateway-websocket:
    container_name: gdax-gateway-websocket
    build:
      context: ..
      dockerfile: deploy/build/gateway-websocket-nodejs/Dockerfile
    image: gdax-gateway-websocket:latest
