version: "2"

services:
  influxdb:
    image: dockerproxy-cwfr1.rd.francetelecom.fr/influxdb
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"

  chronograf:
    image: dockerproxy-cwfr1.rd.francetelecom.fr/chronograf
    volumes:
      - ./data/chronograf:/var/lib/chronograf
    ports:
      - "8888:8888"
    links:
      - influxdb

  rabbitmq-management:
    image: dockerproxy-cwfr1.rd.francetelecom.fr/rabbitmq:3-management
    hostname: "gdax-rabbit"
    ports:
      - "5672:5672"
      - "8080:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  gdaxauthservice:
    container_name: gdaxauth-service
    build:
      context: ..
      dockerfile: build/gdaxauthservice/Dockerfile
    image: gdaxauth-service:latest
    expose:
      - 28081
