version: "2"

services:
  influxdb:
    image: dockerproxy-cwfr1.rd.francetelecom.fr/influxdb
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"

  chronograf:
    image: dockerproxy-cwfr1.rd.francetelecom.fr/chronograf
    volumes:
      - ./data/chronograf:/var/lib/chronograf
    ports:
      - "8888:8888"
    links:
      - influxdb

  rabbitmq:
      image: dockerproxy-cwfr1.rd.francetelecom.fr/rabbitmq:3
      ports:
        - "5672:5672"

  rabbitmq-management:
    depends_on:
      - rabbitmq
    image: dockerproxy-cwfr1.rd.francetelecom.fr/rabbitmq:3-management
    ports:
      - "8080:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password